LANGUAGES = {
    "Tr": {
        "indir": "⬇ İndir",
        "iptal": "✖ İptal Et",
        "link_placeholder": "Video bağlantısını buraya yapıştırın",
        "uyari": "Lütfen bir video linki girin!",
        "kalite": "Kalite",
        "sistem_bildirim_checkbox": "İşlem tamamlandığında bildir",
        "koyu_modda_baslat_checkbox": "Koyu modda başlat\t",
        "bildirim_button":"🔔",
        "indirme_iptal_edildi": "İndirme iptal edildi",
        "info_title": "Başarılı",
        "operation_completed": "İşlem tamamlandı!",
        "error_title": "Hata",
        "warning_title": "Uyarı",
        "empty_url_warning": "Lütfen bir video bağlantısı girin!",
        "invalid_url_warning": "Lütfen geçerli bir bağlantı girin",
        "quality_error_message": "Lütfen bir kalite seçin",
        "preview_info_title": "Önizleme",
        "system_notification_message": "Sistem bildirimi bu şekilde görünür.",
        "download_complete_message": "Video başarıyla indirildi.",
        "audio_download_complete_message": "Ses dosyası başarıyla indirildi.",
        "indirme_baslatiliyor": "İndirme başlatılıyor...",
        "islem_devam_ediyor": "İndirme işlemi devam ediyor, lütfen bekleyin...",
        "indirme_iptal_ediliyor": "İndirme iptal ediliyor...",
        "oynatma_listesi_checkbox_text": "Oynatma listesini indir",
        "file_not_found_error": "'unins000.exe' dosyası bulunamadı. Uygulama kurulu olmayabilir veya dosya silinmiş olabilir.",
        "uninstall_button": "Kaldır",
        "download_video_format_error": "Geçersiz bağlantı veya platform korumaları (ör. SABR)"
                                       " nedeniyle uygun format bulunamadı.\n\n"
                                       "Lütfen bağlantının geçerli ve erişilebilir olduğundan emin olun.",
        "2160p": "2160p ⁴ᴷ",
        "1440p": "1440p ²ᴷ",
        "1080p": "1080p ᴴᴰ",
        "720p": "720p",
        "audio": "Ses",

    },
    "En": {
        "indir": "⬇ Download",
        "iptal": "✖ Cancel",
        "link_placeholder": "Paste video link here",
        "uyari": "Please enter a video link!",
        "kalite": "Quality",
        "sistem_bildirim_checkbox" : "Notify on completion",
        "koyu_modda_baslat_checkbox": "Start in dark mode \t\t",
        "bildirim_button":"🔔",
        "indirme_iptal_edildi": "Download cancelled",
        "info_title": "Success",
        "operation_completed": "Download completed!",
        "error_title": "Error",
        "warning_title": "Warning",
        "empty_url_warning": "Please enter a video link!",
        "invalid_url_warning": "Please enter a valid URL",
        "quality_error_message": "Please select a quality",
        "preview_info_title": "Preview",
        "system_notification_message": "This is how the system notification will look.",
        "download_complete_message": "Video downloaded successfully.",
        "audio_download_complete_message": "Audio file downloaded successfully.",
        "indirme_baslatiliyor": "Downloading...",
        "islem_devam_ediyor": "The download is in progress, please wait...",
        "indirme_iptal_ediliyor": "Download is canceled..",
        "oynatma_listesi_checkbox_text": "Download playlist",
        "file_not_found_error": "'unins000.exe' was not found. The application may not be installed or the file might have been deleted.",
        "uninstall_button": "Uninstall",
        "download_video_format_error": (
            "No suitable format found due to invalid URL or platform protections (e.g., SABR).\n\n"
            "Please ensure the link is valid and accessible."
        ),
        "2160p": "2160p ⁴ᴷ",
        "1440p": "1440p ²ᴷ",
        "1080p": "1080p ᴴᴰ",
        "720p": "720p",
        "audio": "Audio",

    }
}
