LANGUAGES = {
    "Tr": {
        "download": "⬇ İndir",
        "cancel": "❌ İptal Et",
        "link_placeholder": "Video bağlantısını buraya yapıştırın",
        "kalite": "Kalite",
        "system_notification_checkbox": "İşlem tamamlandığında bildir",
        "start_in_dark_mode_checkbox": "Koyu modda başlat\t",
        "preview_notification_button":"🔔",
        "download_canceled_message": "İndirme iptal edildi",
        "operation_completed_message": "İşlem tamamlandı!",
        "error_title": "Hata",
        "warning_title": "Uyarı",
        "empty_url_warning": "Lütfen bir video bağlantısı girin!",
        "invalid_url_warning": "Lütfen geçerli bir bağlantı girin",
        "not_a_video_url_warning": "Bu bir video bağlantısı değil (arama sonucu, kanal veya oynatma listesi sayfası olabilir).\n\nLütfen tek bir videonun bağlantısını girin.",
        "quality_error_message": "Lütfen bir kalite seçin",
        "preview_info_title": "Önizleme",
        "preview_loading_message": "Yükleniyor...",
        "system_notification_message": "Bu bir test bildirimidir.",
        "download_complete_message": "Video başarıyla indirildi.",
        "audio_download_complete_message": "Ses dosyası başarıyla indirildi.",
        "download_starting_message": "İndirme başlatılıyor...",
        "operation_in_progress_message": "İndirme işlemi devam ediyor, lütfen bekleyin...",
        "merging_message": "Video işleniyor...",
        "download_canceling_message": "İndirme iptal ediliyor...",
        "playlist_checkbox_text": "Oynatma listesini indir",
        "file_not_found_error": "'unins000.exe' dosyası bulunamadı. Uygulama kurulu olmayabilir veya dosya silinmiş olabilir.",
        "uninstall_button": "Kaldır",
        "download_video_format_error": "Geçersiz bağlantı veya platform korumaları"
                                       " nedeniyle içerik indirilemedi.\n\n"
                                       "Lütfen bağlantının geçerli ve erişilebilir olduğundan emin olun.",
        "ffmpeg_not_found_error": "FFmpeg bulunamadı, indirme başlatılamadı.\n\n"
                                  "Eğer projeyi GitHub'dan indirdiyseniz, terminalde şu komutu çalıştırın:\n"
                                  "pip install imageio-ffmpeg\n\n"
                                  "Kurulum tamamlandıktan sonra uygulamayı yeniden başlatın.",
        "unexpected_error_message": "Beklenmeyen bir hata oluştu. Lütfen tekrar deneyin.",
        "uninstall_app_title": "Uygulamayı Kaldır",
        "uninstall_app_message": "Uygulama bilgisayarınızdan kaldırılacaktır.\nDevam etmek istiyor musunuz?",
        "audio": "Ses",
        "queue_remaining_label": "Kuyrukta kalanlar",
        "queue_title_label": "Kuyruk",
        "clear_queue_button": "Kuyruğu Temizle",
        "add_to_queue_button": "➕ Sıraya Ekle",
        "ytdlp_downloading_message": "yt-dlp hazırlanıyor... %{percent}",
        "ytdlp_downloading_indeterminate_message": "yt-dlp hazırlanıyor...",
        "ytdlp_checking_message": "Güncellemeler kontrol ediliyor...",
        "ytdlp_setup_failed_generic_message": "yt-dlp indirilemedi.\n\nLütfen tekrar deneyin. Sorun devam ederse şu hata koduyla birlikte bildirin:\n{error}",
        "retry_button": "🔄 Tekrar Dene",
        "ytdlp_update_failed_network_message": "yt-dlp güncellenemedi (internet bağlantısı yok).\n\nMevcut sürüm kullanılacak.",
        "ytdlp_update_failed_generic_message": "yt-dlp güncellenemedi.\n\nMevcut sürüm kullanılacak. Hata: {error}",
        "choose_folder_button": "📁 İndirme Konumunu Seç",
        "cut_label": "Kes",
        "copy_label": "Kopyala",
        "paste_label": "Yapıştır",
        "select_all_label": "Tümünü Seç",

        # Hata sınıflandırma
        "error_no_internet": "İnternet bağlantısı yok.\n\nLütfen bağlantınızı kontrol edip tekrar deneyin.",
        "error_video_not_found": "Video bulunamadı.\n\nBağlantı yanlış olabilir veya video kaldırılmış olabilir.",
        "error_unsupported_url": "Bu bağlantı desteklenen bir video sitesine ait değil.\n\nLütfen desteklenen bir platformdan tek bir video bağlantısı girin.",
        "error_video_private": "Bu video gizli (private).\n\nGizli videolar indirilemez.",
        "error_age_restricted": "Bu video için yaş doğrulaması gerekiyor.\n\nYaş kısıtlaması olan videolar bu uygulamayla indirilemez.",
        "error_access_blocked": "YouTube bu isteği engelledi (bot koruması ya da çok sık istek).\n\nBir süre bekleyip tekrar deneyin.",
        "error_format_not_found": "Bu video için uygun bir format bulunamadı.",
        "error_ffmpeg_generic": "Video ve ses birleştirilirken bir hata oluştu.",
        "error_disk_full": "Disk alanı yetersiz.\n\nLütfen yer açıp tekrar deneyin.",
        "error_permission": "Dosyaya yazma izni yok.\n\nİndirme konumunun yazma izinlerini kontrol edin.",
        "error_unknown_ytdlp": "İndirme sırasında bilinmeyen bir hata oluştu.",
        "error_download_stalled": "İndirme askıda kaldı ve durduruldu.\n\n"
                                  "Bu videoyla ilgili yt-dlp bir sorunla karşılaşmış olabilir. "
                                  "Lütfen tekrar deneyin veya farklı bir video ile test edin.",

        # Güncelleme kontrolü
        "check_updates_button": "🔄 Güncellemeleri Kontrol Et",
        "update_check_title": "Güncelleme Kontrolü",
        "already_latest_message": "En son sürümü kullanıyorsunuz ({version}).",
        "update_available_title": "Güncelleme Mevcut",
        "update_available_message": "Yeni bir sürüm ({version}) mevcut. Şimdi güncellensin mi?",
        "update_no_installer_message": "Yeni bir sürüm ({version}) mevcut ancak indirilebilir bir kurulum dosyası bulunamadı.\n\nGitHub'daki sürüm sayfası tarayıcıda açılsın mı?",
        "update_check_failed_message": "Güncellemeler kontrol edilemedi.\n\nLütfen internet bağlantınızı kontrol edip tekrar deneyin.",
        "update_downloading_message": "Güncelleme indiriliyor...",

    },
    "En": {
        "download": "⬇ Download",
        "cancel": "❌ Cancel",
        "link_placeholder": "Paste video link here",
        "kalite": "Quality",
        "system_notification_checkbox" : "Notify on completion",
        "start_in_dark_mode_checkbox": "Start in dark mode \t\t",
        "preview_notification_button":"🔔",
        "download_canceled_message": "Download cancelled",
        "operation_completed_message": "Download completed!",
        "error_title": "Error",
        "warning_title": "Warning",
        "empty_url_warning": "Please enter a video link!",
        "invalid_url_warning": "Please enter a valid URL",
        "not_a_video_url_warning": "This isn't a video link (it may be a search results page, channel page, or playlist page).\n\nPlease enter a link to a single video.",
        "quality_error_message": "Please select a quality",
        "preview_info_title": "Preview",
        "preview_loading_message": "Loading...",
        "system_notification_message": "This is a test notification.",
        "download_complete_message": "Video downloaded successfully.",
        "audio_download_complete_message": "Audio file downloaded successfully.",
        "download_starting_message": "Starting download...",
        "operation_in_progress_message": "Download in progress, please wait...",
        "merging_message": "Processing video...",
        "download_canceling_message": "Download is canceled..",
        "playlist_checkbox_text": "Download playlist",
        "file_not_found_error": "'unins000.exe' was not found. The application may not be installed or the file might have been deleted.",
        "uninstall_button": "Uninstall",
        "download_video_format_error": (
            "Content could not be downloaded due to an invalid link or platform protections.\n\n"
            "Please ensure the link is valid and accessible."
        ),
        "ffmpeg_not_found_error": (
                   "FFmpeg was not found, download could not start.\n\n"
                   "If you cloned this project from GitHub, run this in a terminal:\n"
                   "pip install imageio-ffmpeg\n\n"
                  "Then restart the application."
              ),
        "unexpected_error_message": "An unexpected error occurred. Please try again.",
        "uninstall_app_title": "Uninstall Application",
        "uninstall_app_message": "This will remove the application from your computer.\nDo you want to continue?",
        "audio": "Audio",
        "queue_remaining_label": "Remaining in queue",
        "queue_title_label": "Queue",
        "clear_queue_button": "Clear Queue",
        "add_to_queue_button": "➕ Add to Queue",
        "ytdlp_downloading_message": "Preparing yt-dlp... %{percent}",
        "ytdlp_downloading_indeterminate_message": "Preparing yt-dlp...",
        "ytdlp_checking_message": "Checking for updates...",
        "ytdlp_setup_failed_generic_message": "Failed to download yt-dlp.\n\nPlease try again. If the problem continues, report it with this error:\n{error}",
        "retry_button": "🔄 Retry",
        "ytdlp_update_failed_network_message": "Couldn't update yt-dlp (no internet connection).\n\nUsing the existing version.",
        "ytdlp_update_failed_generic_message": "Couldn't update yt-dlp.\n\nUsing the existing version. Error: {error}",
        "choose_folder_button": "📁 Choose Download Location",
        "cut_label": "Cut",
        "copy_label": "Copy",
        "paste_label": "Paste",
        "select_all_label": "Select All",

        # Error classification
        "error_no_internet": "No internet connection.\n\nPlease check your connection and try again.",
        "error_video_not_found": "Video not found.\n\nThe link may be wrong, or the video may have been removed.",
        "error_unsupported_url": "This link isn't from a supported video site.\n\nPlease enter a link to a single video from a supported platform.",
        "error_video_private": "This video is private.\n\nPrivate videos can't be downloaded.",
        "error_age_restricted": "This video requires age verification.\n\nAge-restricted videos can't be downloaded with this app.",
        "error_access_blocked": "YouTube blocked this request (bot protection or too many requests).\n\nWait a while and try again.",
        "error_format_not_found": "No suitable format was found for this video.",
        "error_ffmpeg_generic": "An error occurred while merging the video and audio.",
        "error_disk_full": "Not enough disk space.\n\nFree up some space and try again.",
        "error_permission": "Permission denied while writing the file.\n\nCheck the write permissions of the download location.",
        "error_unknown_ytdlp": "An unknown error occurred during download.",
        "error_download_stalled": "The download got stuck and was stopped.\n\n"
                                  "yt-dlp may have run into an issue with this video. "
                                  "Please try again, or test with a different video.",

        # Update check
        "check_updates_button": "🔄 Check for Updates",
        "update_check_title": "Check for Updates",
        "already_latest_message": "You already have the latest version ({version}).",
        "update_available_title": "Update Available",
        "update_available_message": "A new version ({version}) is available. Update now?",
        "update_no_installer_message": "A new version ({version}) is available, but no downloadable installer was found.\n\nOpen the release page on GitHub in your browser?",
        "update_check_failed_message": "Could not check for updates.\n\nPlease check your internet connection and try again.",
        "update_downloading_message": "Downloading update...",

    },
    "Es": {
        "download": "⬇ Descargar",
        "cancel": "❌ Cancelar",
        "link_placeholder": "Pega aquí el enlace del video",
        "kalite": "Calidad",
        "system_notification_checkbox": "Notificar al completar",
        "start_in_dark_mode_checkbox": "Iniciar en modo oscuro\t",
        "preview_notification_button": "🔔",
        "download_canceled_message": "Descarga cancelada",
        "operation_completed_message": "¡Descarga completada!",
        "error_title": "Error",
        "warning_title": "Advertencia",
        "empty_url_warning": "¡Introduce un enlace de video!",
        "invalid_url_warning": "Introduce una URL válida",
        "not_a_video_url_warning": "Este no es un enlace de video (puede ser una página de resultados de búsqueda, un canal o una lista de reproducción).\n\nIntroduce el enlace de un solo video.",
        "quality_error_message": "Selecciona una calidad",
        "preview_info_title": "Vista previa",
        "preview_loading_message": "Cargando...",
        "system_notification_message": "Esta es una notificación de prueba.",
        "download_complete_message": "El video se descargó correctamente.",
        "audio_download_complete_message": "El archivo de audio se descargó correctamente.",
        "download_starting_message": "Iniciando descarga...",
        "operation_in_progress_message": "La descarga está en curso, espera por favor...",
        "merging_message": "Procesando video...",
        "download_canceling_message": "Cancelando descarga...",
        "playlist_checkbox_text": "Descargar lista de reproducción",
        "file_not_found_error": "No se encontró el archivo 'unins000.exe'. Es posible que la aplicación no esté instalada o que el archivo haya sido eliminado.",
        "uninstall_button": "Eliminar",
        "download_video_format_error": (
            "No se pudo descargar el contenido debido a un enlace no válido o a las protecciones de la plataforma.\n\n"
            "Asegúrate de que el enlace sea válido y accesible."
        ),
        "ffmpeg_not_found_error": (
            "No se encontró FFmpeg y no se pudo iniciar la descarga.\n\n"
            "Si clonaste este proyecto desde GitHub, ejecuta este comando en una terminal:\n"
            "pip install imageio-ffmpeg\n\n"
            "Después, reinicia la aplicación."
        ),
        "unexpected_error_message": "Ocurrió un error inesperado. Inténtalo de nuevo.",
        "uninstall_app_title": "Desinstalar aplicación",
        "uninstall_app_message": "La aplicación se eliminará de tu computadora.\n¿Quieres continuar?",
        "audio": "Audio",
        "queue_remaining_label": "Restantes en la cola",
        "queue_title_label": "Cola",
        "clear_queue_button": "Vaciar cola",
        "add_to_queue_button": "➕ Añadir a la cola",
        "ytdlp_downloading_message": "Preparando yt-dlp... %{percent}",
        "ytdlp_downloading_indeterminate_message": "Preparando yt-dlp...",
        "ytdlp_checking_message": "Buscando actualizaciones...",
        "ytdlp_setup_failed_generic_message": "No se pudo descargar yt-dlp.\n\nInténtalo de nuevo. Si el problema continúa, repórtalo con este error:\n{error}",
        "retry_button": "🔄 Reintentar",
        "ytdlp_update_failed_network_message": "No se pudo actualizar yt-dlp (sin conexión a Internet).\n\nSe utilizará la versión existente.",
        "ytdlp_update_failed_generic_message": "No se pudo actualizar yt-dlp.\n\nSe utilizará la versión existente. Error: {error}",
        "choose_folder_button": "📁 Elegir ubicación de descarga",
        "cut_label": "Cortar",
        "copy_label": "Copiar",
        "paste_label": "Pegar",
        "select_all_label": "Seleccionar todo",

        # Clasificación de errores
        "error_no_internet": "No hay conexión a Internet.\n\nComprueba tu conexión e inténtalo de nuevo.",
        "error_video_not_found": "No se encontró el video.\n\nEl enlace puede ser incorrecto o el video puede haber sido eliminado.",
        "error_unsupported_url": "Este enlace no pertenece a un sitio de videos compatible.\n\nIntroduce el enlace de un solo video de una plataforma compatible.",
        "error_video_private": "Este video es privado.\n\nLos videos privados no se pueden descargar.",
        "error_age_restricted": "Este video requiere verificación de edad.\n\nLos videos con restricción de edad no se pueden descargar con esta aplicación.",
        "error_access_blocked": "YouTube bloqueó esta solicitud (protección contra bots o demasiadas solicitudes).\n\nEspera un momento e inténtalo de nuevo.",
        "error_format_not_found": "No se encontró un formato adecuado para este video.",
        "error_ffmpeg_generic": "Ocurrió un error al combinar el video y el audio.",
        "error_disk_full": "No hay suficiente espacio en el disco.\n\nLibera espacio e inténtalo de nuevo.",
        "error_permission": "No tienes permiso para escribir el archivo.\n\nComprueba los permisos de escritura de la ubicación de descarga.",
        "error_unknown_ytdlp": "Ocurrió un error desconocido durante la descarga.",
        "error_download_stalled": "La descarga se quedó bloqueada y se detuvo.\n\n"
                                  "Es posible que yt-dlp haya encontrado un problema con este video. "
                                  "Inténtalo de nuevo o prueba con otro video.",

        # Comprobación de actualizaciones
        "check_updates_button": "🔄 Buscar actualizaciones",
        "update_check_title": "Buscar actualizaciones",
        "already_latest_message": "Ya tienes la última versión ({version}).",
        "update_available_title": "Actualización disponible",
        "update_available_message": "Hay una nueva versión ({version}) disponible. ¿Actualizar ahora?",
        "update_no_installer_message": "Hay una nueva versión ({version}) disponible, pero no se encontró un instalador descargable.\n\n¿Quieres abrir la página de la versión en GitHub en tu navegador?",
        "update_check_failed_message": "No se pudieron comprobar las actualizaciones.\n\nComprueba tu conexión a Internet e inténtalo de nuevo.",
        "update_downloading_message": "Descargando actualización...",
    }

}