LANGUAGES = {
    "Tr": {
        "download": "⬇ İndir",
        "cancel": "❌ İptal Et",
        "link_placeholder": "Video bağlantısını buraya yapıştırın",
        "uyari": "Lütfen bir video linki girin!",
        "kalite": "Kalite",
        "system_notification_checkbox": "İşlem tamamlandığında bildir",
        "start_in_dark_mode_checkbox": "Koyu modda başlat\t",
        "preview_notification_button":"🔔",
        "download_canceled_message": "İndirme iptal edildi",
        "info_title": "Başarılı",
        "operation_completed_message": "İşlem tamamlandı!",
        "error_title": "Hata",
        "warning_title": "Uyarı",
        "empty_url_warning": "Lütfen bir video bağlantısı girin!",
        "invalid_url_warning": "Lütfen geçerli bir bağlantı girin",
        "quality_error_message": "Lütfen bir kalite seçin",
        "preview_info_title": "Önizleme",
        "system_notification_message": "Bu bir test bildirimidir.",
        "download_complete_message": "Video başarıyla indirildi.",
        "audio_download_complete_message": "Ses dosyası başarıyla indirildi.",
        "download_starting_message": "İndirme başlatılıyor...",
        "operation_in_progress_message": "İndirme işlemi devam ediyor, lütfen bekleyin...",
        "download_canceling_message": "İndirme iptal ediliyor...",
        "playlist_checkbox_text": "Oynatma listesini indir",
        "file_not_found_error": "'unins000.exe' dosyası bulunamadı. Uygulama kurulu olmayabilir veya dosya silinmiş olabilir.",
        "uninstall_button": "Kaldır",
        "download_video_format_error": "Geçersiz bağlantı veya platform korumaları (ör. SABR)"
                                       " nedeniyle içerik indirilemedi\n\n"
                                       "Lütfen bağlantının geçerli ve erişilebilir olduğundan emin olun.",
        "uninstall_app_title": "Uygulamayı kaldır",
        "uninstall_app_message": "Uygulama bilgisayarınızdan kaldırılacaktır.\nDevam etmek istiyor musunuz?",
        "2160p": "2160p ⁴ᴷ",
        "1440p": "1440p ²ᴷ",
        "1080p": "1080p ᴴᴰ",
        "720p": "720p",
        "audio": "Ses",
        "queue_remaining_label": "Kuyrukta kalan",
        "queue_title_label": "Kuyruk",
        "clear_queue_button": "Kuyruğu Temizle",
        "add_to_queue_button": "➕ Sıraya Ekle",
        "ytdlp_downloading_message": "yt-dlp hazırlanıyor... %{percent}",
        "ytdlp_downloading_indeterminate_message": "yt-dlp hazırlanıyor...",
        "ytdlp_checking_message": "Güncellemeler kontrol ediliyor...",
        "choose_folder_button": "📁 İndirme Konumunu Seç",
        "cut_label": "Kes",
        "copy_label": "Kopyala",
        "paste_label": "Yapıştır",
        "select_all_label": "Tümünü Seç",

    },
    "En": {
        "download": "⬇ Download",
        "cancel": "❌ Cancel",
        "link_placeholder": "Paste video link here",
        "uyari": "Please enter a video link!",
        "kalite": "Quality",
        "system_notification_checkbox" : "Notify on completion",
        "start_in_dark_mode_checkbox": "Start in dark mode \t\t",
        "preview_notification_button":"🔔",
        "download_canceled_message": "Download cancelled",
        "info_title": "Success",
        "operation_completed_message": "Download completed!",
        "error_title": "Error",
        "warning_title": "Warning",
        "empty_url_warning": "Please enter a video link!",
        "invalid_url_warning": "Please enter a valid URL",
        "quality_error_message": "Please select a quality",
        "preview_info_title": "Preview",
        "system_notification_message": "This is a test notification.",
        "download_complete_message": "Video downloaded successfully.",
        "audio_download_complete_message": "Audio file downloaded successfully.",
        "download_starting_message": "Downloading...",
        "operation_in_progress_message": "The download is in progress, please wait...",
        "download_canceling_message": "Download is canceled..",
        "playlist_checkbox_text": "Download playlist",
        "file_not_found_error": "'unins000.exe' was not found. The application may not be installed or the file might have been deleted.",
        "uninstall_button": "Uninstall",
        "download_video_format_error": (
            "Content could not be downloaded due to an invalid link or platform protections (e.g., SABR).\n\n"
            "Please ensure the link is valid and accessible."
        ),
        "uninstall_app_title": "Uninstall app",
        "uninstall_app_message": "This will remove the application from your computer.\nDo you want to continue?",
        "2160p": "2160p ⁴ᴷ",
        "1440p": "1440p ²ᴷ",
        "1080p": "1080p ᴴᴰ",
        "720p": "720p",
        "audio": "Audio",
        "queue_remaining_label": "Remaining in queue",
        "queue_title_label": "Queue",
        "clear_queue_button": "Clear Queue",
        "add_to_queue_button": "➕ Add to Queue",
        "ytdlp_downloading_message": "Preparing yt-dlp... %{percent}",
        "ytdlp_downloading_indeterminate_message": "Preparing yt-dlp...",
        "ytdlp_checking_message": "Checking for updates...",
        "choose_folder_button": "📁 Choose Download Location",
        "cut_label": "Cut",
        "copy_label": "Copy",
        "paste_label": "Paste",
        "select_all_label": "Select All",

    }
}